### ISSUE TITLE
I can't convert my model into barracuda format. Plz help me.

### ISSUE THREAD

**Issue by StanislavTrubin** [mantasp/barracuda-release#1]
Hi, mantasp.
I feel thanks that I can get help from you.
Today, I tried to convert my trained models (trained in customvision.ai (azure)) into barracuda format to reach the end point in unity with this new plugin.
But I couldn't convert them myself because of assertion error or key not found errors.
I tried both tensorflow_to_barracuda.py & onnx_to_barracuda.py files.
I want to get help as soon as possible due the project is urgent to me.
Thanks very much.
And I prefer to contract  via skype for faster response.
Plz find me live:pathos821 on skype.
Here are my models & all data.
[Model.zip](https://github.com/mantasp/barracuda-release/files/3178456/Model.zip)

**Comment by KozykinRoman** [comment]
For note, I blocked all "assert" command lines of tensorflow_to_barracuda.py & barracuda.py files when I convert the pb file into bytes format. Then I could successfully get the bytes file but when I run the model in unity then the following errors occurred. I don't know why because it is embedded.
Here are the screenshots of what I have done with this new plugin. Plz help me.
![Tested the model with python script(It works well)](https://user-images.githubusercontent.com/50035118/57708994-1df26780-761f-11e9-9cdf-93fb47a76559.png)
[Screenshots.zip](https://github.com/mantasp/barracuda-release/files/3178545/Screenshots.zip)

**Comment by rash1994** [comment]
Hi KozykinRoman, 

Could you convert your model from .pb to .nn ?

**Comment by mantasp** [comment]
Barracuda 0.3.0 shipped with new ONNX importer, which works directly in editor just drop in your ONNX file there (and later you can pass it as NNModel asset into ModelLoader). Please try if it improved your model import.
